apiVersion: v1
kind: Pod
metadata:
  name: job1
spec:
  containers:
  - args:
    - bidirectional_rnn.py
    - /root/job1.csv
    - job1
    command:
    - python
    image: wzheng33/birnn
    name: lenet-test-epoch
    volumeMounts:
    - mountPath: /root/
      name: task-pv-storage
  restartPolicy: Never
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs